CREATE DATABASE INDUSTRYS;

USE INDUSTRYS;

CREATE TABLE SHANTALA(id int ,NAME_INDUSTRY varchar(40) PRIMARY KEY,NO_OF_WORKERS INT CHECK (NO_OF_WORKERS<=20), HR_NAME varchar(10),
DATE varchar(12),STATUS varchar(10),SHIFTS INT,TIME timestamp,LOCATION varchar(40),TYPE varchar(40) );


SELECT * FROM INDUSTRYS;

INSERT INTO SHANTALA VALUES(1,'SHANTALA_INDUSTRYS',2000,'MADHU_K','07/09/2023','ACTIVE',3,NOW(),'MACHENAHALLI','AUTOMOBILE_PRODUCTS');

INSERT INTO SHANTALA VALUES(2,'MALNAD_INDUSTRYS',400,'KUMAR J','08/09/2023','INACTIVE',3,NOW(),'MACHENAHALLI','AUTOMOBILE_PRODUCTS');

INSERT INTO SHANTALA VALUES(3,'SHIVA_INDUSTRYS',4500,'SHIVA','09/09/2023','ACTIVE',3,NOW(),'SHIVMOGA','KRACKERS_PRODUCTS');

INSERT INTO SHANTALA VALUES(4,'SRUTHI_INDUSTRYS',741,'KARTHIK','10/09/2023','INACTIVE',3,NOW(),'NRPURA','FLAMMER_PRODUCTS');

INSERT INTO SHANTALA VALUES(5,'KUMAR_INDUSTRYS',894,'VINAY','11/09/2023','ACTIVE',3,NOW(),'C','AHAMRAJANAGAR,CONSTRUCTION_PRODUCTS');



SELECT* FROM SHANTALA;


CREATE DATABASE PROVISION_STORE;

USE PROVISION_STORE;

CREATE TABLE STORE(id int ,STORE_NAME varchar(40) PRIMARY KEY,NO_OF_WORKERS INT CHECK (NO_OF_WORKERS<=9), OWNER_NAME varchar(10),
DATE varchar(12),STATUS varchar(10),SHIFTS INT,TIME timestamp,LOCATION varchar(40),TYPE varchar(40),FOREIGN KEY(DATE) REFERENCES SHANTALA(LOCATION));

INSERT INTO STORE VALUES(1,'RAGAVENDRA_STORE',5,'VINAY_H_S','7/09/2023','ACTIVE',1,NOW(),'SRIRAMPURAM','PROVISTION_STORE_ITEMS');

INSERT INTO STORE VALUES(2,'LAKSHMI_STORE',6,'HARSHITH','3/09/2023','ACTIVE',1,NOW(),'NR PURA','PROVISTION_STORE_ITEMS');

INSERT INTO STORE VALUES(3,'JANANNI_STORE',7,'KUMAR','4/09/2023','ACTIVE',1,NOW(),'NARSIMHARAJPURA','PROVISTION_STORE_ITEMS');

INSERT INTO STORE VALUES(4,'VINAYAAKA_STORE',7,'RAJU','5/09/2023','ACTIVE',1,NOW(),'DAVANGERE','PROVISTION_STORE_ITEMS');

INSERT INTO STORE VALUES(5,'MANGALURU_STORE',9,'VIKAS','6/09/2023','ACTIVE',1,NOW(),'T_B_CIRCLE','PROVISTION_STORE_ITEMS');


SELECT * FROM STORE;


CREATE DATABASE FABRICS;

USE FABRICS;

CREATE TABLE FASION(ID INT, N_STORE varchar(40),GST varchar(30),DATE varchar(14),
TIME timestamp,LOCATION varchar(40),P_REMAIN INT CHECK(P_REMAIN>=20),P_SALESED INT,SALER_BY varchar(14),PRICE INT,FOREIGN KEY(DATE) REFERENCES INDUSTRYS(LOCATION));


INSERT INTO FASION VALUES(1,'BENGALURU_TEXTILE','GSTIN1452F1247','7/9/2023',NOW(),'T_B_ROAD',13,5,'NEHA',6845);

INSERT INTO FASION VALUES(2,'GANESH_TEXTILE','GSTIN1552F1247','8/9/2023',NOW(),'M_G_ROAD',15,5,'MOHAN',4587);

INSERT INTO FASION VALUES(3,'VIKAS_TEXTILE','GSTIN19852F1247','9/9/2023',NOW(),'SRIRAMPURAM',16,5,'VINAY_H_S',745);

INSERT INTO FASION VALUES(4,'BAGHYA_TEXTILE','GSTIN14486F1247','9/9/2023',NOW(),'SRINGERI',19,5,'JEEVAN_K',5000);

INSERT INTO FASION VALUES(5,'SRC_TEXTILE','GSTIN1452F4547','4/9/2023',NOW(),'KOPPA',10,5,'DEELEP_F',4000);

SELECT * FROM FASION;